version: '3'

services:
  elasticsearch:
    image: ${OSS_IMAGE}
    hostname: elasticsearch
    container_name: elasticsearch
    networks: 
      - elasticsearch # used by ESv6 kibana
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ${OSS_ENV_VAR:-FOO=bar}
    command: ${ES_COMMAND}
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  opendistro:
    image: ${ES_OPENDISTRO_IMAGE:-rwgrim/docker-noop}
    hostname: elasticsearch-opendistro
    container_name: elasticsearch-opendistro
    environment:
      - cluster.name=opendistro
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - ${OPENSEARCH_PREFIX:-opendistro_security}.ssl.http.enabled=false
      - http.port=9220
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9220:9220
networks:
  elasticsearch:
    driver: bridge
